In [1]:
import pandas as pd

In [37]:
full_df = pd.read_csv("WTG_component_Active.csv")
full_df

,TimeStampLocalSystem,Name,Systemname,Minute10Average
0,2019-10-01 00:10:00.000,Active power reference setpoint,NaN,50
1,2019-10-01 00:10:00.000,Actual active power,NaN,10
2,2019-10-01 00:10:00.000,Blade 1 actual value,Hawa01,2
3,2019-10-01 00:10:00.000,Blade 1 actual value,Hawa02,2
4,2019-10-01 00:10:00.000,Blade 1 actual value,Hawa03,2
...,...,...,...,...
9751523,2020-03-07 11:50:00.000,Wind speed,Hawa25,6
9751524,2020-03-07 11:50:00.000,Wind speed,Hawa26,5
9751525,2020-03-07 11:50:00.000,Wind speed,Hawa27,6
9751526,2020-03-07 11:50:00.000,Wind speed,Hawa28,6
9751527,2020-03-07 11:50:00.000,Wind speed,Hawa29,6

Split feature df test

In [24]:
column_names = full_df.Name.unique().tolist()

column_names

['Active power reference setpoint',
 'Actual active power',
 'Blade 1 actual value',
 'Blade 2 actual value A',
 'Blade 3 actual value A',
 'Gear oil Temperature near heating elements',
 'Gearbox bearing Temperature  Intermediate shaft generator side  (rotor side)',
 'Gearbox bearing Temperature High speed shaft rotor side',
 'Gearbox bearing Temperature Intermediate shaft rotor side',
 'Nacelle position',
 'Power',
 'Temp. bearing A',
 'Temp. bearing B',
 'Temp. gear box bearing',
 'Temp. gearbox',
 'Temp. shaft bearing',
 'Temperature GBX Distributor',
 'Wind direction',
 'Wind speed']

In [22]:
df_names = []

def create_df_names(list):
    for i in list:  
        i = i.replace(" ", "_")
        df_names.append(i)

create_df_names(column_names)

df_names

['Active_power_reference_setpoint',
 'Actual_active_power',
 'Blade_1_actual_value',
 'Blade_2_actual_value_A',
 'Blade_3_actual_value_A',
 'Gear_oil_Temperature_near_heating_elements',
 'Gearbox_bearing_Temperature__Intermediate_shaft_generator_side__(rotor_side)',
 'Gearbox_bearing_Temperature_High_speed_shaft_rotor_side',
 'Gearbox_bearing_Temperature_Intermediate_shaft_rotor_side',
 'Nacelle_position',
 'Power',
 'Temp._bearing_A',
 'Temp._bearing_B',
 'Temp._gear_box_bearing',
 'Temp._gearbox',
 'Temp._shaft_bearing',
 'Temperature_GBX_Distributor',
 'Wind_direction',
 'Wind_speed']

In [46]:
#function to loop through features and pull into df 
# https://stackoverflow.com/questions/48888001/creating-multiple-dataframes-with-a-loop


dict_of_dfs ={}


#loop through each feature
for column, feature_df in zip(column_names, df_names):

    #pull those rows into df 
    dict_of_dfs[feature_df] = full_df.loc[full_df["Name"] == column] #does this need to be f""

    #rename measurement column with feature name 
    dict_of_dfs[feature_df] = dict_of_dfs[feature_df].rename(mapper={"Minute10Average":feature_df}, axis=1)

    #drop name column 
    dict_of_dfs[feature_df] = dict_of_dfs[feature_df].drop(labels=["Name"], axis=1)

Each feature is in a df

Each df is stored in a dictionary, where the key value pairs are df_name: df

Access each feature specific df through dict_of_dfs["df_name"], i.e. dict_of_dfs['Power']

In [42]:
#check that all features are there 
list(dict_of_dfs.keys())

['Active_power_reference_setpoint',
 'Actual_active_power',
 'Blade_1_actual_value',
 'Blade_2_actual_value_A',
 'Blade_3_actual_value_A',
 'Gear_oil_Temperature_near_heating_elements',
 'Gearbox_bearing_Temperature__Intermediate_shaft_generator_side__(rotor_side)',
 'Gearbox_bearing_Temperature_High_speed_shaft_rotor_side',
 'Gearbox_bearing_Temperature_Intermediate_shaft_rotor_side',
 'Nacelle_position',
 'Power',
 'Temp._bearing_A',
 'Temp._bearing_B',
 'Temp._gear_box_bearing',
 'Temp._gearbox',
 'Temp._shaft_bearing',
 'Temperature_GBX_Distributor',
 'Wind_direction',
 'Wind_speed']

* check for count of each measurement
* check for nas

In [70]:
dict_of_dfs["Temp._gearbox"]

            TimeStampLocalSystem Systemname  Temp._gearbox
350      2019-10-01 00:10:00.000     Hawa01             57
351      2019-10-01 00:10:00.000     Hawa02             57
352      2019-10-01 00:10:00.000     Hawa03             56
353      2019-10-01 00:10:00.000     Hawa04             58
354      2019-10-01 00:10:00.000     Hawa05             56
...                          ...        ...            ...
9751452  2020-03-07 11:50:00.000     Hawa25             48
9751453  2020-03-07 11:50:00.000     Hawa26             47
9751454  2020-03-07 11:50:00.000     Hawa27             47
9751455  2020-03-07 11:50:00.000     Hawa28             51
9751456  2020-03-07 11:50:00.000     Hawa29             47

[633583 rows x 3 columns]

In [71]:
dict_of_dfs["Power"]

            TimeStampLocalSystem Systemname  Power
234      2019-10-01 00:10:00.000     Hawa01    427
235      2019-10-01 00:10:00.000     Hawa02    450
236      2019-10-01 00:10:00.000     Hawa03    481
237      2019-10-01 00:10:00.000     Hawa04    483
238      2019-10-01 00:10:00.000     Hawa05    471
...                          ...        ...    ...
9751360  2020-03-07 11:50:00.000     Hawa25    386
9751361  2020-03-07 11:50:00.000     Hawa26    380
9751362  2020-03-07 11:50:00.000     Hawa27    400
9751363  2020-03-07 11:50:00.000     Hawa28    427
9751364  2020-03-07 11:50:00.000     Hawa29    657

[286268 rows x 3 columns]

In [53]:
new_line= "\n"
for df_name in df_names:
    print (f"The count for {df_name} is: {new_line} {dict_of_dfs[df_name].count()}")

The count for Active_power_reference_setpoint is:
 TimeStampLocalSystem               22823
Systemname                             0
Active_power_reference_setpoint    22823
dtype: int64
The count for Actual_active_power is:
 TimeStampLocalSystem    22823
Systemname                  0
Actual_active_power     22823
dtype: int64
The count for Blade_1_actual_value is:
 TimeStampLocalSystem    592631
Systemname              592631
Blade_1_actual_value    592631
dtype: int64
The count for Blade_2_actual_value_A is:
 TimeStampLocalSystem      589243
Systemname                589243
Blade_2_actual_value_A    589243
dtype: int64
The count for Blade_3_actual_value_A is:
 TimeStampLocalSystem      589098
Systemname                589098
Blade_3_actual_value_A    589098
dtype: int64
The count for Gear_oil_Temperature_near_heating_elements is:
 TimeStampLocalSystem                          633583
Systemname                                    633583
Gear_oil_Temperature_near_heating_elements    633583
dtype: int64
The count for Gearbox_bearing_Temperature__Intermediate_shaft_generator_side__(rotor_side) is:
 TimeStampLocalSystem                                                            633583
Systemname                                                                      633583
Gearbox_bearing_Temperature__Intermediate_shaft_generator_side__(rotor_side)    633583
dtype: int64
The count for Gearbox_bearing_Temperature_High_speed_shaft_rotor_side is:
 TimeStampLocalSystem                                       633583
Systemname                                                 633583
Gearbox_bearing_Temperature_High_speed_shaft_rotor_side    633583
dtype: int64
The count for Gearbox_bearing_Temperature_Intermediate_shaft_rotor_side is:
 TimeStampLocalSystem                                         633583
Systemname                                                   633583
Gearbox_bearing_Temperature_Intermediate_shaft_rotor_side    633583
dtype: int64
The count for Nacelle_position is:
 TimeStampLocalSystem    633583
Systemname              633583
Nacelle_position        633583
dtype: int64
The count for Power is:
 TimeStampLocalSystem    286268
Systemname              286268
Power                   286268
dtype: int64
The count for Temp._bearing_A is:
 TimeStampLocalSystem    633583
Systemname              633583
Temp._bearing_A         633583
dtype: int64
The count for Temp._bearing_B is:
 TimeStampLocalSystem    633583
Systemname              633583
Temp._bearing_B         633583
dtype: int64
The count for Temp._gear_box_bearing is:
 TimeStampLocalSystem      633583
Systemname                633583
Temp._gear_box_bearing    633583
dtype: int64
The count for Temp._gearbox is:
 TimeStampLocalSystem    633583
Systemname              633583
Temp._gearbox           633583
dtype: int64
The count for Temp._shaft_bearing is:
 TimeStampLocalSystem    633583
Systemname              633583
Temp._shaft_bearing     633583
dtype: int64
The count for Temperature_GBX_Distributor is:
 TimeStampLocalSystem           633583
Systemname                     633583
Temperature_GBX_Distributor    633583
dtype: int64
The count for Wind_direction is:
 TimeStampLocalSystem    22823
Systemname                  0
Wind_direction          22823
dtype: int64
The count for Wind_speed is:
 TimeStampLocalSystem    656406
Systemname              633583
Wind_speed              656406
dtype: int64

In [69]:
# table of counts 
values = []

for df_name in df_names:
    values.append(dict_of_dfs[df_name][df_name].count())

counts_info = {"Feature":df_names, "Count of Measurements":values}

counts_df = pd.DataFrame(counts_info)

counts_df.sort_values(by="Count of Measurements")

                                              Feature  Count of Measurements
0                     Active_power_reference_setpoint                  22823
1                                 Actual_active_power                  22823
17                                     Wind_direction                  22823
10                                              Power                 286268
4                              Blade_3_actual_value_A                 589098
3                              Blade_2_actual_value_A                 589243
2                                Blade_1_actual_value                 592631
16                        Temperature_GBX_Distributor                 633583
15                                Temp._shaft_bearing                 633583
14                                      Temp._gearbox                 633583
13                             Temp._gear_box_bearing                 633583
12                                    Temp._bearing_B                 633583
9                                    Nacelle_position                 633583
8   Gearbox_bearing_Temperature_Intermediate_shaft...                 633583
7   Gearbox_bearing_Temperature_High_speed_shaft_r...                 633583
6   Gearbox_bearing_Temperature__Intermediate_shaf...                 633583
5          Gear_oil_Temperature_near_heating_elements                 633583
11                                    Temp._bearing_A                 633583
18                                         Wind_speed                 656406

Join test

* maybe use map instead of join to add each column back? 
* should we fill na with 0? => no, fill with values around it (average of two points around it)
* current: leave NaN

Filter

*

In [ ]:
# unnecessary function = just use df.column.unique() as done above 
# def get_features(feature):

#     feature_list_unique = [ ]

#     for feature in feature_list:
#         if feature in feature_list_unique:
#             continue
#         else:
#             feature_list_unique.append(feature)
#     return feature_list_unique

# feature_list_unique = get_features(feature_list)

Inidividual Test of pull single feature into df => create function for this

In [ ]:
#create individual feature df
windspeed = df.loc[df["Name"] == "Wind speed"]

In [ ]:
windspeed

In [ ]:
#rename measurement to feature name 
windspeed.rename(mapper={"Minute10Average":"WindSpeed"}, axis=1)

In [ ]:
#drop name column 
windspeed.drop(labels=["Name"], axis=1)

In [ ]:
# Actual active power	

aapower = df.loc[df["Name"] == "Actual active power"]

In [ ]:
aapower

In [ ]:
aapowersystemname = aapower["Systemname"]

In [ ]:
aapower.count()