In [1]:
import pandas as pd

In [2]:
full_df = pd.read_csv("../Resources/EDPR_1.csv")

In [3]:
fault_df = pd.read_csv("../Resources/Major_Faults_1.csv")

In [8]:
full_df.drop(columns=["Unnamed: 0"], inplace=True)
fault_df.drop(columns=["Unnamed: 0"], inplace=True)

In [6]:
full_df

,time_stamp,turbine_id,amb_temp_avg,amb_winddir_abs_avg,amb_winddir_relative_avg,amb_windspeed_avg,blds_pitchangle_avg,cont_hub_temp_avg,cont_top_temp_avg,cont_vcp_chokcoiltemp_avg,...,hvtrafo_phase1_temp_avg,hvtrafo_phase2_temp_avg,hvtrafo_phase3_temp_avg,hyd_oil_temp_avg,nac_direction_avg,nac_temp_avg,rtr_rpm_avg,spin_temp_avg,suspect,wind_bucket
0,2016-01-01 00:00:00,T11,18,199.1,-7.8,5.3,-1.4,28,41,90,...,46,51,46,30,206.9,27,11.3,20,0.0,5
1,2016-01-01 00:10:00,T11,18,207.5,0.6,5.7,-1.7,28,41,90,...,46,51,46,30,206.9,27,11.5,20,0.0,6
2,2016-01-01 00:20:00,T11,18,190.5,-16.5,6.1,-1.9,28,41,90,...,46,52,46,30,206.9,27,11.9,20,0.0,6
3,2016-01-01 00:30:00,T11,18,214.6,7.6,6.3,-2.0,28,41,90,...,47,52,47,30,206.9,27,12.2,20,0.0,6
4,2016-01-01 00:40:00,T06,18,197.6,-9.8,4.9,-1.1,27,38,94,...,45,48,45,31,207.4,29,11.1,20,0.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227872,2017-12-31 23:40:00,T11,15,328.1,0.0,5.4,-1.5,25,38,89,...,46,51,46,28,328.2,23,11.2,17,0.0,5
227873,2017-12-31 23:50:00,T06,15,325.1,0.0,4.7,-1.0,26,30,102,...,45,49,45,28,325.1,23,11.1,18,0.0,5
227874,2017-12-31 23:50:00,T07,15,337.7,2.9,5.3,-1.5,25,26,93,...,71,73,71,30,334.8,21,11.1,17,0.0,5
227875,2017-12-31 23:50:00,T01,15,349.0,1.2,5.4,-1.6,25,37,88,...,64,71,64,26,347.8,25,11.1,17,0.0,5
227876,2017-12-31 23:50:00,T11,15,333.8,2.4,5.5,-1.6,25,38,89,...,46,51,46,28,331.5,23,11.2,17,0.0,6

In [9]:
fault_df

,time_stamp,turbine_id,fault,description
0,2017-08-11 13:10:00,T01,TRANSFORMER,Transformer fan damaged
1,2017-10-17 08:40:00,T06,GEARBOX,Gearbox bearings damaged
2,2017-08-19 09:50:00,T06,HYDRAULIC_GROUP,Oil leakage in Hub
3,2017-08-20 06:10:00,T07,GENERATOR_BEARING,Generator bearings damaged
4,2017-08-21 14:50:00,T07,GENERATOR,Generator damaged
5,2017-06-17 11:40:00,T07,HYDRAULIC_GROUP,Oil leakage in Hub
6,2017-10-19 10:10:00,T07,HYDRAULIC_GROUP,Oil leakage in Hub
7,2017-04-26 18:10:00,T11,HYDRAULIC_GROUP,Hydraulic group error in the brake circuit
8,2017-09-12 15:30:00,T11,HYDRAULIC_GROUP,Hydraulic group error in the brake circuit
9,2016-07-18 02:10:00,T01,GEARBOX,Gearbox pump damaged
10,2016-07-11 19:50:00,T06,GENERATOR,Generator replaced
11,2016-07-24 17:00:00,T06,GENERATOR,Generator temperature sensor failure
12,2016-09-04 08:10:00,T06,GENERATOR,High temperature generator error
13,2016-10-27 16:30:00,T06,GENERATOR,Generator replaced
14,2016-10-02 17:10:00,T06,GENERATOR,Refrigeration system and temperature sensors i...
15,2016-04-04 18:50:00,T06,HYDRAULIC_GROUP,Error in pitch regulation
16,2016-04-30 12:40:00,T07,GENERATOR_BEARING,High temperature in generator bearing (replace...
17,2016-07-10 03:50:00,T07,TRANSFORMER,High temperature transformer
18,2016-08-23 02:20:00,T07,TRANSFORMER,High temperature transformer. Transformer refr...
19,2016-03-03 19:00:00,T11,GENERATOR,Electric circuit error in generator
20,2016-10-17 17:40:00,T11,HYDRAULIC_GROUP,Hydraulic group error in the brake circuit

In [15]:
full_df.shape

(227877, 43)

In [31]:
#join

merged_df = pd.merge(full_df, fault_df,how="outer")

In [32]:
merged_df.shape

(227884, 45)

In [35]:
merged_df

,time_stamp,turbine_id,amb_temp_avg,amb_winddir_abs_avg,amb_winddir_relative_avg,amb_windspeed_avg,blds_pitchangle_avg,cont_hub_temp_avg,cont_top_temp_avg,cont_vcp_chokcoiltemp_avg,...,hvtrafo_phase3_temp_avg,hyd_oil_temp_avg,nac_direction_avg,nac_temp_avg,rtr_rpm_avg,spin_temp_avg,suspect,wind_bucket,fault,description
0,2016-01-01 00:00:00,T11,18.0,199.1,-7.8,5.3,-1.4,28.0,41.0,90.0,...,46.0,30.0,206.9,27.0,11.3,20.0,0.0,5.0,NaN,NaN
1,2016-01-01 00:10:00,T11,18.0,207.5,0.6,5.7,-1.7,28.0,41.0,90.0,...,46.0,30.0,206.9,27.0,11.5,20.0,0.0,6.0,NaN,NaN
2,2016-01-01 00:20:00,T11,18.0,190.5,-16.5,6.1,-1.9,28.0,41.0,90.0,...,46.0,30.0,206.9,27.0,11.9,20.0,0.0,6.0,NaN,NaN
3,2016-01-01 00:30:00,T11,18.0,214.6,7.6,6.3,-2.0,28.0,41.0,90.0,...,47.0,30.0,206.9,27.0,12.2,20.0,0.0,6.0,NaN,NaN
4,2016-01-01 00:40:00,T06,18.0,197.6,-9.8,4.9,-1.1,27.0,38.0,94.0,...,45.0,31.0,207.4,29.0,11.1,20.0,0.0,5.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227879,2017-09-12 15:30:00,T11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HYDRAULIC_GROUP,Hydraulic group error in the brake circuit
227880,2016-07-11 19:50:00,T06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GENERATOR,Generator replaced
227881,2016-04-30 12:40:00,T07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GENERATOR_BEARING,High temperature in generator bearing (replace...
227882,2016-03-03 19:00:00,T11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GENERATOR,Electric circuit error in generator
227883,2016-10-17 17:40:00,T11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,HYDRAULIC_GROUP,Hydraulic group error in the brake circuit

Note: there are 14 major faults that merged in line with measurements, there are 7 major faults that did not find a match in an existing measurement. So 7 faults have NaN for all measurements - does this cause an issue?

In [27]:
# explore non matching faults 
# merged_df.loc[0]["2016-04-30 12:40:00"]

KeyError: '2016-04-30 12:40:00'

map 0/1 for fault/no fault
* pull column to series
* not null as int 
* put series into fault column, drop description

In [17]:

fault_series = merged_df["fault"]

In [38]:
fault_series = fault_series.notnull().astype("int")

In [39]:
fault_series

0         0
1         0
2         0
3         0
4         0
         ..
227879    1
227880    1
227881    1
227882    1
227883    1
Name: fault, Length: 227884, dtype: int32

In [40]:
merged_df["fault"] = fault_series

In [42]:
merged_df.drop(columns="description", inplace=True)

In [43]:
merged_df

,time_stamp,turbine_id,amb_temp_avg,amb_winddir_abs_avg,amb_winddir_relative_avg,amb_windspeed_avg,blds_pitchangle_avg,cont_hub_temp_avg,cont_top_temp_avg,cont_vcp_chokcoiltemp_avg,...,hvtrafo_phase2_temp_avg,hvtrafo_phase3_temp_avg,hyd_oil_temp_avg,nac_direction_avg,nac_temp_avg,rtr_rpm_avg,spin_temp_avg,suspect,wind_bucket,fault
0,2016-01-01 00:00:00,T11,18.0,199.1,-7.8,5.3,-1.4,28.0,41.0,90.0,...,51.0,46.0,30.0,206.9,27.0,11.3,20.0,0.0,5.0,0
1,2016-01-01 00:10:00,T11,18.0,207.5,0.6,5.7,-1.7,28.0,41.0,90.0,...,51.0,46.0,30.0,206.9,27.0,11.5,20.0,0.0,6.0,0
2,2016-01-01 00:20:00,T11,18.0,190.5,-16.5,6.1,-1.9,28.0,41.0,90.0,...,52.0,46.0,30.0,206.9,27.0,11.9,20.0,0.0,6.0,0
3,2016-01-01 00:30:00,T11,18.0,214.6,7.6,6.3,-2.0,28.0,41.0,90.0,...,52.0,47.0,30.0,206.9,27.0,12.2,20.0,0.0,6.0,0
4,2016-01-01 00:40:00,T06,18.0,197.6,-9.8,4.9,-1.1,27.0,38.0,94.0,...,48.0,45.0,31.0,207.4,29.0,11.1,20.0,0.0,5.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227879,2017-09-12 15:30:00,T11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
227880,2016-07-11 19:50:00,T06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
227881,2016-04-30 12:40:00,T07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
227882,2016-03-03 19:00:00,T11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
227883,2016-10-17 17:40:00,T11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

To CSV, To RDS

In [44]:
from sqlalchemy import create_engine
engine = create_engine("postgresql://postgres:password@wind-turbine-analysis.chv2nnusygyy.us-west-1.rds.amazonaws.com:5432/wind_turbine_analysis")

In [ ]:
merged_df.to_sql("merged_major_main", engine)