In [1]:
import pandas as pd

In [2]:
full_df = pd.read_csv("..\Resources\EDPR.csv")
full_df

,Unnamed: 0,Time_Stamp,Turbine_ID,Amb_Temp_Avg,Amb_WindDir_Abs_Avg,Amb_WindDir_Relative_Avg,Amb_WindSpeed_Avg,Blds_PitchAngle_Avg,Cont_Hub_Temp_Avg,Cont_Top_Temp_Avg,...,HVTrafo_Phase1_Temp_Avg,HVTrafo_Phase2_Temp_Avg,HVTrafo_Phase3_Temp_Avg,Hyd_Oil_Temp_Avg,Nac_Direction_Avg,Nac_Temp_Avg,Rtr_RPM_Avg,Spin_Temp_Avg,Suspect,Wind_Bucket
0,0,01 /01 /2016 00:00,T11,18,199.1,-7.8,5.3,-1.4,28,41,...,46,51,46,30,206.9,27,11.3,20,0.0,5
1,1,01 /01 /2016 00:10,T11,18,207.5,0.6,5.7,-1.7,28,41,...,46,51,46,30,206.9,27,11.5,20,0.0,6
2,2,01 /01 /2016 00:20,T11,18,190.5,-16.5,6.1,-1.9,28,41,...,46,52,46,30,206.9,27,11.9,20,0.0,6
3,3,01 /01 /2016 00:30,T11,18,214.6,7.6,6.3,-2.0,28,41,...,47,52,47,30,206.9,27,12.2,20,0.0,6
4,4,01 /01 /2016 00:40,T06,18,197.6,-9.8,4.9,-1.1,27,38,...,45,48,45,31,207.4,29,11.1,20,0.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227872,227872,12 /31 /2017 23:40,T11,15,328.1,0.0,5.4,-1.5,25,38,...,46,51,46,28,328.2,23,11.2,17,0.0,5
227873,227873,12 /31 /2017 23:50,T06,15,325.1,0.0,4.7,-1.0,26,30,...,45,49,45,28,325.1,23,11.1,18,0.0,5
227874,227874,12 /31 /2017 23:50,T07,15,337.7,2.9,5.3,-1.5,25,26,...,71,73,71,30,334.8,21,11.1,17,0.0,5
227875,227875,12 /31 /2017 23:50,T01,15,349.0,1.2,5.4,-1.6,25,37,...,64,71,64,26,347.8,25,11.1,17,0.0,5
227876,227876,12 /31 /2017 23:50,T11,15,333.8,2.4,5.5,-1.6,25,38,...,46,51,46,28,331.5,23,11.2,17,0.0,6

In [3]:
full_df.columns

Index(['Unnamed: 0', 'Time_Stamp', 'Turbine_ID', 'Amb_Temp_Avg',
       'Amb_WindDir_Abs_Avg', 'Amb_WindDir_Relative_Avg', 'Amb_WindSpeed_Avg',
       'Blds_PitchAngle_Avg', 'Cont_Hub_Temp_Avg', 'Cont_Top_Temp_Avg',
       'Cont_VCP_ChokcoilTemp_Avg', 'Cont_VCP_Temp_Avg',
       'Cont_VCP_WtrTemp_Avg', 'Gear_Bear_Temp_Avg', 'Gear_Oil_Temp_Avg',
       'Gen_Bear2_Temp_Avg', 'Gen_Bear_Temp_Avg', 'Gen_Phase1_Temp_Avg',
       'Gen_Phase2_Temp_Avg', 'Gen_Phase3_Temp_Avg', 'Gen_RPM_Avg',
       'Gen_SlipRing_Temp_Avg', 'Grd_Busbar_Temp_Avg',
       'Grd_InverterPhase1_Temp_Avg', 'Grd_Prod_CurPhse1_Avg',
       'Grd_Prod_CurPhse2_Avg', 'Grd_Prod_CurPhse3_Avg', 'Grd_Prod_Pwr_Avg',
       'Grd_Prod_VoltPhse1_Avg', 'Grd_Prod_VoltPhse2_Avg',
       'Grd_Prod_VoltPhse3_Avg', 'Grd_RtrInvPhase1_Temp_Avg',
       'Grd_RtrInvPhase2_Temp_Avg', 'Grd_RtrInvPhase3_Temp_Avg',
       'HVTrafo_Phase1_Temp_Avg', 'HVTrafo_Phase2_Temp_Avg',
       'HVTrafo_Phase3_Temp_Avg', 'Hyd_Oil_Temp_Avg', 'Nac_Direction_Avg',
       'Nac_Temp_Avg', 'Rtr_RPM_Avg', 'Spin_Temp_Avg', 'Suspect',
       'Wind_Bucket'],
      dtype='object')

In [4]:
full_df[full_df["Susepct"] == "bad"]

KeyError: 'Susepct'

In [ ]:
Suspect = full_df["Susepct"]

In [ ]:
Suspect = Suspect.map({"bad": 1})

In [ ]:
full_df["Susepct"] = Suspect

In [ ]:
full_df["Susepct"] = full_df["Susepct"].fillna(0)

In [ ]:
full_df = full_df.rename(columns={"times_stamp":"Times_Stamp","Susepct":"Suspect", "wind bucket": "Wind_Bucket"})

In [4]:
full_df["Time_Stamp"] = full_df["Time_Stamp"].apply(pd.to_datetime)

# full_df["Times_Stamp"] = full_df["Times_Stamp"].dt.strftime('%m /%d /%Y %H:%M')

In [6]:
column_names_alph = ['Times_Stamp','Turbine_ID','Amb_Temp_Avg','Amb_WindDir_Abs_Avg',
'Amb_WindDir_Relative_Avg','Amb_WindSpeed_Avg','Blds_PitchAngle_Avg','Cont_Hub_Temp_Avg','Cont_Top_Temp_Avg',
'Cont_VCP_ChokcoilTemp_Avg','Cont_VCP_Temp_Avg','Cont_VCP_WtrTemp_Avg','Gear_Bear_Temp_Avg',
'Gear_Oil_Temp_Avg','Gen_Bear2_Temp_Avg','Gen_Bear_Temp_Avg','Gen_Phase1_Temp_Avg',
'Gen_Phase2_Temp_Avg','Gen_Phase3_Temp_Avg','Gen_RPM_Avg','Gen_SlipRing_Temp_Avg',
'Grd_Busbar_Temp_Avg','Grd_InverterPhase1_Temp_Avg','Grd_Prod_CurPhse1_Avg','Grd_Prod_CurPhse2_Avg',
'Grd_Prod_CurPhse3_Avg','Grd_Prod_Pwr_Avg','Grd_Prod_VoltPhse1_Avg','Grd_Prod_VoltPhse2_Avg',
'Grd_Prod_VoltPhse3_Avg','Grd_RtrInvPhase1_Temp_Avg','Grd_RtrInvPhase2_Temp_Avg',
'Grd_RtrInvPhase3_Temp_Avg','HVTrafo_Phase1_Temp_Avg','HVTrafo_Phase2_Temp_Avg',
'HVTrafo_Phase3_Temp_Avg','Hyd_Oil_Temp_Avg','Nac_Direction_Avg',
'Nac_Temp_Avg','Rtr_RPM_Avg','Spin_Temp_Avg','Suspect','Wind_Bucket']

In [7]:
full_df

,Unnamed: 0,Time_Stamp,Turbine_ID,Amb_Temp_Avg,Amb_WindDir_Abs_Avg,Amb_WindDir_Relative_Avg,Amb_WindSpeed_Avg,Blds_PitchAngle_Avg,Cont_Hub_Temp_Avg,Cont_Top_Temp_Avg,...,HVTrafo_Phase1_Temp_Avg,HVTrafo_Phase2_Temp_Avg,HVTrafo_Phase3_Temp_Avg,Hyd_Oil_Temp_Avg,Nac_Direction_Avg,Nac_Temp_Avg,Rtr_RPM_Avg,Spin_Temp_Avg,Suspect,Wind_Bucket
0,0,2016-01-01 00:00:00,T11,18,199.1,-7.8,5.3,-1.4,28,41,...,46,51,46,30,206.9,27,11.3,20,0.0,5
1,1,2016-01-01 00:10:00,T11,18,207.5,0.6,5.7,-1.7,28,41,...,46,51,46,30,206.9,27,11.5,20,0.0,6
2,2,2016-01-01 00:20:00,T11,18,190.5,-16.5,6.1,-1.9,28,41,...,46,52,46,30,206.9,27,11.9,20,0.0,6
3,3,2016-01-01 00:30:00,T11,18,214.6,7.6,6.3,-2.0,28,41,...,47,52,47,30,206.9,27,12.2,20,0.0,6
4,4,2016-01-01 00:40:00,T06,18,197.6,-9.8,4.9,-1.1,27,38,...,45,48,45,31,207.4,29,11.1,20,0.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227872,227872,2017-12-31 23:40:00,T11,15,328.1,0.0,5.4,-1.5,25,38,...,46,51,46,28,328.2,23,11.2,17,0.0,5
227873,227873,2017-12-31 23:50:00,T06,15,325.1,0.0,4.7,-1.0,26,30,...,45,49,45,28,325.1,23,11.1,18,0.0,5
227874,227874,2017-12-31 23:50:00,T07,15,337.7,2.9,5.3,-1.5,25,26,...,71,73,71,30,334.8,21,11.1,17,0.0,5
227875,227875,2017-12-31 23:50:00,T01,15,349.0,1.2,5.4,-1.6,25,37,...,64,71,64,26,347.8,25,11.1,17,0.0,5
227876,227876,2017-12-31 23:50:00,T11,15,333.8,2.4,5.5,-1.6,25,38,...,46,51,46,28,331.5,23,11.2,17,0.0,6

In [9]:
#lowercase column names for sql query
full_df.columns = full_df.columns.str.lower()

In [12]:
full_df

,time_stamp,turbine_id,amb_temp_avg,amb_winddir_abs_avg,amb_winddir_relative_avg,amb_windspeed_avg,blds_pitchangle_avg,cont_hub_temp_avg,cont_top_temp_avg,cont_vcp_chokcoiltemp_avg,...,hvtrafo_phase1_temp_avg,hvtrafo_phase2_temp_avg,hvtrafo_phase3_temp_avg,hyd_oil_temp_avg,nac_direction_avg,nac_temp_avg,rtr_rpm_avg,spin_temp_avg,suspect,wind_bucket
0,2016-01-01 00:00:00,T11,18,199.1,-7.8,5.3,-1.4,28,41,90,...,46,51,46,30,206.9,27,11.3,20,0.0,5
1,2016-01-01 00:10:00,T11,18,207.5,0.6,5.7,-1.7,28,41,90,...,46,51,46,30,206.9,27,11.5,20,0.0,6
2,2016-01-01 00:20:00,T11,18,190.5,-16.5,6.1,-1.9,28,41,90,...,46,52,46,30,206.9,27,11.9,20,0.0,6
3,2016-01-01 00:30:00,T11,18,214.6,7.6,6.3,-2.0,28,41,90,...,47,52,47,30,206.9,27,12.2,20,0.0,6
4,2016-01-01 00:40:00,T06,18,197.6,-9.8,4.9,-1.1,27,38,94,...,45,48,45,31,207.4,29,11.1,20,0.0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
227872,2017-12-31 23:40:00,T11,15,328.1,0.0,5.4,-1.5,25,38,89,...,46,51,46,28,328.2,23,11.2,17,0.0,5
227873,2017-12-31 23:50:00,T06,15,325.1,0.0,4.7,-1.0,26,30,102,...,45,49,45,28,325.1,23,11.1,18,0.0,5
227874,2017-12-31 23:50:00,T07,15,337.7,2.9,5.3,-1.5,25,26,93,...,71,73,71,30,334.8,21,11.1,17,0.0,5
227875,2017-12-31 23:50:00,T01,15,349.0,1.2,5.4,-1.6,25,37,88,...,64,71,64,26,347.8,25,11.1,17,0.0,5
227876,2017-12-31 23:50:00,T11,15,333.8,2.4,5.5,-1.6,25,38,89,...,46,51,46,28,331.5,23,11.2,17,0.0,6

In [13]:
full_df.to_csv("../Resources/EDPR_1.csv")

In [14]:
from sqlalchemy import create_engine
engine = create_engine("postgresql://postgres:password@wind-turbine-analysis.chv2nnusygyy.us-west-1.rds.amazonaws.com:5432/wind_turbine_analysis")

In [ ]:
#write to rds 
full_df.to_sql("main", engine)

Fault table to csv 

* problem with datetime dtype

https://pandas.pydata.org/docs/reference/api/pandas.Timestamp.round.html

freq can also be a multiple of a single unit, like â€˜5Tâ€™ (i.e. 5 minutes):

ts.round(freq='5T')
Timestamp('2020-03-14 15:35:00')

In [15]:
fault_df = pd.read_csv("../Resources/Major_Faults.csv")

In [16]:
fault_df

,Turbine_ID,Unnamed: 1,Unnamed: 2,Unnamed: 3
0,T01,TRANSFORMER,2017-08-11T13:14:00+00:00,Transformer fan damaged
1,T06,GEARBOX,2017-10-17T08:38:00+00:00,Gearbox bearings damaged
2,T06,HYDRAULIC_GROUP,2017-08-19T09:47:00+00:00,Oil leakage in Hub
3,T07,GENERATOR_BEARING,2017-08-20T06:08:00+00:00,Generator bearings damaged
4,T07,GENERATOR,2017-08-21T14:47:00+00:00,Generator damaged
5,T07,HYDRAULIC_GROUP,2017-06-17T11:35:00+00:00,Oil leakage in Hub
6,T07,HYDRAULIC_GROUP,2017-10-19T10:11:00+00:00,Oil leakage in Hub
7,T11,HYDRAULIC_GROUP,2017-04-26T18:06:00+00:00,Hydraulic group error in the brake circuit
8,T11,HYDRAULIC_GROUP,2017-09-12T15:30:00+00:00,Hydraulic group error in the brake circuit
9,T01,GEARBOX,2016-07-18T02:10:00+00:00,Gearbox pump damaged
10,T06,GENERATOR,2016-07-11T19:48:00+00:00,Generator replaced
11,T06,GENERATOR,2016-07-24T17:01:00+00:00,Generator temperature sensor failure
12,T06,GENERATOR,2016-09-04T08:08:00+00:00,High temperature generator error
13,T06,GENERATOR,2016-10-27T16:26:00+00:00,Generator replaced
14,T06,GENERATOR,2016-10-02T17:08:00+00:00,Refrigeration system and temperature sensors i...
15,T06,HYDRAULIC_GROUP,2016-04-04T18:53:00+00:00,Error in pitch regulation
16,T07,GENERATOR_BEARING,2016-04-30T12:40:00+00:00,High temperature in generator bearing (replace...
17,T07,TRANSFORMER,2016-07-10T03:46:00+00:00,High temperature transformer
18,T07,TRANSFORMER,2016-08-23T02:21:00+00:00,High temperature transformer. Transformer refr...
19,T11,GENERATOR,2016-03-03T19:00:00+00:00,Electric circuit error in generator
20,T11,HYDRAULIC_GROUP,2016-10-17T17:44:00+00:00,Hydraulic group error in the brake circuit

In [7]:
fault_df.count()

Turbine_ID    21
Unnamed: 1    21
Unnamed: 2    21
Unnamed: 3    21
dtype: int64

In [17]:
fault_df = fault_df.rename({"Unnamed: 2":"time_stamp",
                    "Turbine_ID":"turbine_id",
                    "Unnamed: 1":"fault",
                    "Unnamed: 3":"description"}, axis=1)

In [18]:
fault_df = fault_df[["time_stamp", "turbine_id", "fault", "description"]]

In [19]:
fault_df

,time_stamp,turbine_id,fault,description
0,2017-08-11T13:14:00+00:00,T01,TRANSFORMER,Transformer fan damaged
1,2017-10-17T08:38:00+00:00,T06,GEARBOX,Gearbox bearings damaged
2,2017-08-19T09:47:00+00:00,T06,HYDRAULIC_GROUP,Oil leakage in Hub
3,2017-08-20T06:08:00+00:00,T07,GENERATOR_BEARING,Generator bearings damaged
4,2017-08-21T14:47:00+00:00,T07,GENERATOR,Generator damaged
5,2017-06-17T11:35:00+00:00,T07,HYDRAULIC_GROUP,Oil leakage in Hub
6,2017-10-19T10:11:00+00:00,T07,HYDRAULIC_GROUP,Oil leakage in Hub
7,2017-04-26T18:06:00+00:00,T11,HYDRAULIC_GROUP,Hydraulic group error in the brake circuit
8,2017-09-12T15:30:00+00:00,T11,HYDRAULIC_GROUP,Hydraulic group error in the brake circuit
9,2016-07-18T02:10:00+00:00,T01,GEARBOX,Gearbox pump damaged
10,2016-07-11T19:48:00+00:00,T06,GENERATOR,Generator replaced
11,2016-07-24T17:01:00+00:00,T06,GENERATOR,Generator temperature sensor failure
12,2016-09-04T08:08:00+00:00,T06,GENERATOR,High temperature generator error
13,2016-10-27T16:26:00+00:00,T06,GENERATOR,Generator replaced
14,2016-10-02T17:08:00+00:00,T06,GENERATOR,Refrigeration system and temperature sensors i...
15,2016-04-04T18:53:00+00:00,T06,HYDRAULIC_GROUP,Error in pitch regulation
16,2016-04-30T12:40:00+00:00,T07,GENERATOR_BEARING,High temperature in generator bearing (replace...
17,2016-07-10T03:46:00+00:00,T07,TRANSFORMER,High temperature transformer
18,2016-08-23T02:21:00+00:00,T07,TRANSFORMER,High temperature transformer. Transformer refr...
19,2016-03-03T19:00:00+00:00,T11,GENERATOR,Electric circuit error in generator
20,2016-10-17T17:44:00+00:00,T11,HYDRAULIC_GROUP,Hydraulic group error in the brake circuit

In [20]:
fault_df.dtypes

time_stamp     object
turbine_id     object
fault          object
description    object
dtype: object

In [21]:
fault_df["time_stamp"] = fault_df["time_stamp"].apply(pd.to_datetime)

In [22]:
fault_df.dtypes

time_stamp     datetime64[ns, UTC]
turbine_id                  object
fault                       object
description                 object
dtype: object

In [16]:
#round demo

fault_df["time_stamp"][0].round(freq="10T")

Timestamp('2017-08-11 13:10:00+0000', tz='UTC')

In [27]:
#round loop
times = fault_df["time_stamp"]
round_times = []
for i in times:
    round_times.append(i.round(freq="10T").replace(tzinfo=None))

In [30]:
#rounded time to df 
fault_df["time_stamp"] = round_times

In [27]:
# changed => both tables have datetime for time_stamp instead of strftime 
# format timestamp to match main table 
# fault_df["time_stamp"] = fault_df["time_stamp"].dt.strftime('%m /%d /%Y %H:%M')

In [31]:
fault_df

,time_stamp,turbine_id,fault,description
0,2017-08-11 13:10:00,T01,TRANSFORMER,Transformer fan damaged
1,2017-10-17 08:40:00,T06,GEARBOX,Gearbox bearings damaged
2,2017-08-19 09:50:00,T06,HYDRAULIC_GROUP,Oil leakage in Hub
3,2017-08-20 06:10:00,T07,GENERATOR_BEARING,Generator bearings damaged
4,2017-08-21 14:50:00,T07,GENERATOR,Generator damaged
5,2017-06-17 11:40:00,T07,HYDRAULIC_GROUP,Oil leakage in Hub
6,2017-10-19 10:10:00,T07,HYDRAULIC_GROUP,Oil leakage in Hub
7,2017-04-26 18:10:00,T11,HYDRAULIC_GROUP,Hydraulic group error in the brake circuit
8,2017-09-12 15:30:00,T11,HYDRAULIC_GROUP,Hydraulic group error in the brake circuit
9,2016-07-18 02:10:00,T01,GEARBOX,Gearbox pump damaged
10,2016-07-11 19:50:00,T06,GENERATOR,Generator replaced
11,2016-07-24 17:00:00,T06,GENERATOR,Generator temperature sensor failure
12,2016-09-04 08:10:00,T06,GENERATOR,High temperature generator error
13,2016-10-27 16:30:00,T06,GENERATOR,Generator replaced
14,2016-10-02 17:10:00,T06,GENERATOR,Refrigeration system and temperature sensors i...
15,2016-04-04 18:50:00,T06,HYDRAULIC_GROUP,Error in pitch regulation
16,2016-04-30 12:40:00,T07,GENERATOR_BEARING,High temperature in generator bearing (replace...
17,2016-07-10 03:50:00,T07,TRANSFORMER,High temperature transformer
18,2016-08-23 02:20:00,T07,TRANSFORMER,High temperature transformer. Transformer refr...
19,2016-03-03 19:00:00,T11,GENERATOR,Electric circuit error in generator
20,2016-10-17 17:40:00,T11,HYDRAULIC_GROUP,Hydraulic group error in the brake circuit

In [32]:
full_df.to_csv("../Resources/Major_Faults_1.csv")

In [31]:
#write to rds using same engine as main table 
fault_df.to_sql("major_faults", engine)